
- name: Update zsh config
  sudo: no
  tags: dotfiles
  git:  repo=ssh://git@github.com/elliottt/oh-my-zsh.git
        accept_hostkey=yes
        dest=~/.oh-my-zsh

  notify: Create .zshrc symlink

- name: Update tmux config
  sudo: no
  tags: dotfiles
  git:  repo=ssh://git@github.com/elliottt/tmux-config.git
        accept_hostkey=yes
        dest=~/.tmux

  notify: Create .tmux.conf symlink

- name: Update vim config
  sudo: no
  tags: dotfiles
  git:  repo=ssh://git@github.com/elliottt/vim-config.git
        accept_hostkey=yes
        dest=~/.vim

  notify: Update vim plugins
